// Code generated by mdatagen. DO NOT EDIT.

package metadatatest

import (
	"testing"

	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/otel/sdk/metric/metricdata"
	"go.opentelemetry.io/otel/sdk/metric/metricdata/metricdatatest"

	"github.com/open-telemetry/opentelemetry-collector-contrib/processor/k8sattributesprocessor/internal/metadata"

	"go.opentelemetry.io/collector/component/componenttest"
)

func TestSetupTelemetry(t *testing.T) {
	testTel := componenttest.NewTelemetry()
	tb, err := metadata.NewTelemetryBuilder(testTel.NewTelemetrySettings())
	require.NoError(t, err)
	defer tb.Shutdown()
	tb.OtelsvcK8sIPLookupMiss.Add(t.Context(), 1)
	tb.OtelsvcK8sNamespaceAdded.Add(t.Context(), 1)
	tb.OtelsvcK8sNamespaceDeleted.Add(t.Context(), 1)
	tb.OtelsvcK8sNamespaceUpdated.Add(t.Context(), 1)
	tb.OtelsvcK8sNodeAdded.Add(t.Context(), 1)
	tb.OtelsvcK8sNodeDeleted.Add(t.Context(), 1)
	tb.OtelsvcK8sNodeUpdated.Add(t.Context(), 1)
	tb.OtelsvcK8sPodAdded.Add(t.Context(), 1)
	tb.OtelsvcK8sPodDeleted.Add(t.Context(), 1)
	tb.OtelsvcK8sPodTableSize.Record(t.Context(), 1)
	tb.OtelsvcK8sPodUpdated.Add(t.Context(), 1)
	tb.OtelsvcK8sReplicasetAdded.Add(t.Context(), 1)
	tb.OtelsvcK8sReplicasetDeleted.Add(t.Context(), 1)
	tb.OtelsvcK8sReplicasetUpdated.Add(t.Context(), 1)
	AssertEqualOtelsvcK8sIPLookupMiss(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualOtelsvcK8sNamespaceAdded(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualOtelsvcK8sNamespaceDeleted(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualOtelsvcK8sNamespaceUpdated(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualOtelsvcK8sNodeAdded(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualOtelsvcK8sNodeDeleted(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualOtelsvcK8sNodeUpdated(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualOtelsvcK8sPodAdded(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualOtelsvcK8sPodDeleted(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualOtelsvcK8sPodTableSize(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualOtelsvcK8sPodUpdated(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualOtelsvcK8sReplicasetAdded(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualOtelsvcK8sReplicasetDeleted(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualOtelsvcK8sReplicasetUpdated(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())

	require.NoError(t, testTel.Shutdown(t.Context()))
}
