// Code generated by mdatagen. DO NOT EDIT.

package metadatatest

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/otel/sdk/metric/metricdata"
	"go.opentelemetry.io/otel/sdk/metric/metricdata/metricdatatest"

	"github.com/open-telemetry/opentelemetry-collector-contrib/receiver/solacereceiver/internal/metadata"

	"go.opentelemetry.io/collector/component/componenttest"
)

func TestSetupTelemetry(t *testing.T) {
	testTel := componenttest.NewTelemetry()
	tb, err := metadata.NewTelemetryBuilder(testTel.NewTelemetrySettings())
	require.NoError(t, err)
	defer tb.Shutdown()
	tb.SolacereceiverDroppedEgressSpans.Add(t.Context(), 1)
	tb.SolacereceiverDroppedSpanMessages.Add(t.Context(), 1)
	tb.SolacereceiverFailedReconnections.Add(t.Context(), 1)
	tb.SolacereceiverFatalUnmarshallingErrors.Add(t.Context(), 1)
	tb.SolacereceiverNeedUpgrade.Record(t.Context(), 1)
	tb.SolacereceiverReceivedSpanMessages.Add(t.Context(), 1)
	tb.SolacereceiverReceiverFlowControlRecentRetries.Record(t.Context(), 1)
	tb.SolacereceiverReceiverFlowControlStatus.Record(t.Context(), 1)
	tb.SolacereceiverReceiverFlowControlTotal.Add(t.Context(), 1)
	tb.SolacereceiverReceiverFlowControlWithSingleSuccessfulRetry.Add(t.Context(), 1)
	tb.SolacereceiverReceiverStatus.Record(t.Context(), 1)
	tb.SolacereceiverRecoverableUnmarshallingErrors.Add(t.Context(), 1)
	tb.SolacereceiverReportedSpans.Add(t.Context(), 1)
	AssertEqualSolacereceiverDroppedEgressSpans(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualSolacereceiverDroppedSpanMessages(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualSolacereceiverFailedReconnections(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualSolacereceiverFatalUnmarshallingErrors(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualSolacereceiverNeedUpgrade(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualSolacereceiverReceivedSpanMessages(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualSolacereceiverReceiverFlowControlRecentRetries(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualSolacereceiverReceiverFlowControlStatus(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualSolacereceiverReceiverFlowControlTotal(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualSolacereceiverReceiverFlowControlWithSingleSuccessfulRetry(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualSolacereceiverReceiverStatus(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualSolacereceiverRecoverableUnmarshallingErrors(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualSolacereceiverReportedSpans(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())

	require.NoError(t, testTel.Shutdown(context.Background())) //nolint:usetesting
}
