// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the receiver/awscontainerinsightskueuereceiver component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("awscontainerinsightskueuereceiver")
	ScopeName = "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awscontainerinsightskueuereceiver"
)

const (
	MetricsStability = component.StabilityLevelBeta
)
