// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/confmap"
)

// MetricConfig provides common config for a particular metric.
type MetricConfig struct {
	Enabled          bool `mapstructure:"enabled"`
	enabledSetByUser bool
}

func (ms *MetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}

	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}

	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// MetricsConfig provides config for awsekshyperpodreceiver metrics.
type MetricsConfig struct {
	HyperpodNodeHealthStatusSchedulable                     MetricConfig `mapstructure:"hyperpod_node_health_status_schedulable"`
	HyperpodNodeHealthStatusUnschedulable                   MetricConfig `mapstructure:"hyperpod_node_health_status_unschedulable"`
	HyperpodNodeHealthStatusUnschedulablePendingReboot      MetricConfig `mapstructure:"hyperpod_node_health_status_unschedulable_pending_reboot"`
	HyperpodNodeHealthStatusUnschedulablePendingReplacement MetricConfig `mapstructure:"hyperpod_node_health_status_unschedulable_pending_replacement"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		HyperpodNodeHealthStatusSchedulable: MetricConfig{
			Enabled: true,
		},
		HyperpodNodeHealthStatusUnschedulable: MetricConfig{
			Enabled: true,
		},
		HyperpodNodeHealthStatusUnschedulablePendingReboot: MetricConfig{
			Enabled: true,
		},
		HyperpodNodeHealthStatusUnschedulablePendingReplacement: MetricConfig{
			Enabled: true,
		},
	}
}

// MetricsBuilderConfig is a configuration for awsekshyperpodreceiver metrics builder.
type MetricsBuilderConfig struct {
	Metrics MetricsConfig `mapstructure:"metrics"`
}

func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics: DefaultMetricsConfig(),
	}
}
