// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the autogenerated telemetry and
// build information for the receiver/awsekshyperpodreceiver component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("awsekshyperpodreceiver")
	ScopeName = "github.com/open-telemetry/opentelemetry-collector-contrib/receiver/awsekshyperpodreceiver"
)

const (
	MetricsStability = component.StabilityLevelAlpha
)
