# One of 'breaking', 'deprecation', 'new_component', 'enhancement', 'bug_fix'
change_type: enhancement

# The name of the component, or a single word describing the area of concern, (e.g. filelogreceiver)
component: jmxreceiver

# A brief description of the change.  Surround your text with quotes ("") if it needs to start with a backtick (`).
note: Adds a `password_file` option to the JMX receiver config.

# Mandatory: One or more tracking issues related to the change. You can use the PR number here if no issue exists.
issues: [162]

# (Optional) One or more lines of additional information to render under the primary note.
# These lines will be padded with 2 spaces and then inserted directly into the document.
# Use pipe (|) for multiline entries.
subtext: Allows the passwords to be read in through a separate file instead of being set directly in the |
  receiver YAML. Performs config validation to check if file exists, can be read, and is owner-only accessible. |
  Also sets authentication related fields to `omitempty`.

# e.g. '[aws]'
# Include 'aws' if the change is done done by cwa
# Default: '[user]'
change_logs: [aws]