// Code generated by mdatagen. DO NOT EDIT.

package metadatatest

import (
	"testing"

	"github.com/stretchr/testify/require"
	"go.opentelemetry.io/otel/sdk/metric/metricdata"
	"go.opentelemetry.io/otel/sdk/metric/metricdata/metricdatatest"

	"github.com/open-telemetry/opentelemetry-collector-contrib/processor/groupbyattrsprocessor/internal/metadata"

	"go.opentelemetry.io/collector/component/componenttest"
)

func TestSetupTelemetry(t *testing.T) {
	testTel := componenttest.NewTelemetry()
	tb, err := metadata.NewTelemetryBuilder(testTel.NewTelemetrySettings())
	require.NoError(t, err)
	defer tb.Shutdown()
	tb.ProcessorGroupbyattrsLogGroups.Record(t.Context(), 1)
	tb.ProcessorGroupbyattrsMetricGroups.Record(t.Context(), 1)
	tb.ProcessorGroupbyattrsNumGroupedLogs.Add(t.Context(), 1)
	tb.ProcessorGroupbyattrsNumGroupedMetrics.Add(t.Context(), 1)
	tb.ProcessorGroupbyattrsNumGroupedSpans.Add(t.Context(), 1)
	tb.ProcessorGroupbyattrsNumNonGroupedLogs.Add(t.Context(), 1)
	tb.ProcessorGroupbyattrsNumNonGroupedMetrics.Add(t.Context(), 1)
	tb.ProcessorGroupbyattrsNumNonGroupedSpans.Add(t.Context(), 1)
	tb.ProcessorGroupbyattrsSpanGroups.Record(t.Context(), 1)
	AssertEqualProcessorGroupbyattrsLogGroups(t, testTel,
		[]metricdata.HistogramDataPoint[int64]{{}}, metricdatatest.IgnoreValue(),
		metricdatatest.IgnoreTimestamp())
	AssertEqualProcessorGroupbyattrsMetricGroups(t, testTel,
		[]metricdata.HistogramDataPoint[int64]{{}}, metricdatatest.IgnoreValue(),
		metricdatatest.IgnoreTimestamp())
	AssertEqualProcessorGroupbyattrsNumGroupedLogs(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualProcessorGroupbyattrsNumGroupedMetrics(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualProcessorGroupbyattrsNumGroupedSpans(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualProcessorGroupbyattrsNumNonGroupedLogs(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualProcessorGroupbyattrsNumNonGroupedMetrics(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualProcessorGroupbyattrsNumNonGroupedSpans(t, testTel,
		[]metricdata.DataPoint[int64]{{Value: 1}},
		metricdatatest.IgnoreTimestamp())
	AssertEqualProcessorGroupbyattrsSpanGroups(t, testTel,
		[]metricdata.HistogramDataPoint[int64]{{}}, metricdatatest.IgnoreValue(),
		metricdatatest.IgnoreTimestamp())

	require.NoError(t, testTel.Shutdown(t.Context()))
}
