// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("k8staints")
	ScopeName = "github.com/open-telemetry/opentelemetry-collector-contrib/processor/k8staintsprocessor"
)

const (
	MetricsStability = component.StabilityLevelBeta
	LogsStability    = component.StabilityLevelAlpha
)
