// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/pdata/pcommon"
)

// ResourceBuilder is a helper struct to build resources predefined in metadata.yaml.
// The ResourceBuilder is not thread-safe and must not to be used in multiple goroutines.
type ResourceBuilder struct {
	config ResourceAttributesConfig
	res    pcommon.Resource
}

// NewResourceBuilder creates a new ResourceBuilder. This method should be called on the start of the application.
func NewResourceBuilder(rac ResourceAttributesConfig) *ResourceBuilder {
	return &ResourceBuilder{
		config: rac,
		res:    pcommon.NewResource(),
	}
}

// SetAwsEfaDevice sets provided value as "aws.efa.device" attribute.
func (rb *ResourceBuilder) SetAwsEfaDevice(val string) {
	if rb.config.AwsEfaDevice.Enabled {
		rb.res.Attributes().PutStr("aws.efa.device", val)
	}
}

// SetAwsEfaEniID sets provided value as "aws.efa.eni.id" attribute.
func (rb *ResourceBuilder) SetAwsEfaEniID(val string) {
	if rb.config.AwsEfaEniID.Enabled {
		rb.res.Attributes().PutStr("aws.efa.eni.id", val)
	}
}

// SetAwsEfaPort sets provided value as "aws.efa.port" attribute.
func (rb *ResourceBuilder) SetAwsEfaPort(val string) {
	if rb.config.AwsEfaPort.Enabled {
		rb.res.Attributes().PutStr("aws.efa.port", val)
	}
}

// Emit returns the built resource and resets the internal builder state.
func (rb *ResourceBuilder) Emit() pcommon.Resource {
	r := rb.res
	rb.res = pcommon.NewResource()
	return r
}
