// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"time"

	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/collector/filter"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.opentelemetry.io/collector/receiver"
)

var MetricsInfo = metricsInfo{
	EfaImpairedRemoteConnEvents: metricInfo{
		Name: "efa_impaired_remote_conn_events",
	},
	EfaRdmaReadBytes: metricInfo{
		Name: "efa_rdma_read_bytes",
	},
	EfaRdmaWriteBytes: metricInfo{
		Name: "efa_rdma_write_bytes",
	},
	EfaRdmaWriteRecvBytes: metricInfo{
		Name: "efa_rdma_write_recv_bytes",
	},
	EfaRetransBytes: metricInfo{
		Name: "efa_retrans_bytes",
	},
	EfaRetransPkts: metricInfo{
		Name: "efa_retrans_pkts",
	},
	EfaRetransTimeoutEvents: metricInfo{
		Name: "efa_retrans_timeout_events",
	},
	EfaRxBytes: metricInfo{
		Name: "efa_rx_bytes",
	},
	EfaRxDropped: metricInfo{
		Name: "efa_rx_dropped",
	},
	EfaTxBytes: metricInfo{
		Name: "efa_tx_bytes",
	},
	EfaUnresponsiveRemoteEvents: metricInfo{
		Name: "efa_unresponsive_remote_events",
	},
}

type metricsInfo struct {
	EfaImpairedRemoteConnEvents metricInfo
	EfaRdmaReadBytes            metricInfo
	EfaRdmaWriteBytes           metricInfo
	EfaRdmaWriteRecvBytes       metricInfo
	EfaRetransBytes             metricInfo
	EfaRetransPkts              metricInfo
	EfaRetransTimeoutEvents     metricInfo
	EfaRxBytes                  metricInfo
	EfaRxDropped                metricInfo
	EfaTxBytes                  metricInfo
	EfaUnresponsiveRemoteEvents metricInfo
}

type metricInfo struct {
	Name string
}

type metricEfaImpairedRemoteConnEvents struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills efa_impaired_remote_conn_events metric with initial data.
func (m *metricEfaImpairedRemoteConnEvents) init() {
	m.data.SetName("efa_impaired_remote_conn_events")
	m.data.SetDescription("The number of times EFA SRD connections entered an impaired state resulting in a reduced throughput rate limit")
	m.data.SetUnit("1")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
}

func (m *metricEfaImpairedRemoteConnEvents) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricEfaImpairedRemoteConnEvents) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricEfaImpairedRemoteConnEvents) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricEfaImpairedRemoteConnEvents(cfg MetricConfig) metricEfaImpairedRemoteConnEvents {
	m := metricEfaImpairedRemoteConnEvents{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricEfaRdmaReadBytes struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills efa_rdma_read_bytes metric with initial data.
func (m *metricEfaRdmaReadBytes) init() {
	m.data.SetName("efa_rdma_read_bytes")
	m.data.SetDescription("The number of bytes received using RDMA read operations")
	m.data.SetUnit("By")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
}

func (m *metricEfaRdmaReadBytes) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricEfaRdmaReadBytes) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricEfaRdmaReadBytes) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricEfaRdmaReadBytes(cfg MetricConfig) metricEfaRdmaReadBytes {
	m := metricEfaRdmaReadBytes{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricEfaRdmaWriteBytes struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills efa_rdma_write_bytes metric with initial data.
func (m *metricEfaRdmaWriteBytes) init() {
	m.data.SetName("efa_rdma_write_bytes")
	m.data.SetDescription("The number of bytes written by other instances using RDMA write operations")
	m.data.SetUnit("By")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
}

func (m *metricEfaRdmaWriteBytes) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricEfaRdmaWriteBytes) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricEfaRdmaWriteBytes) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricEfaRdmaWriteBytes(cfg MetricConfig) metricEfaRdmaWriteBytes {
	m := metricEfaRdmaWriteBytes{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricEfaRdmaWriteRecvBytes struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills efa_rdma_write_recv_bytes metric with initial data.
func (m *metricEfaRdmaWriteRecvBytes) init() {
	m.data.SetName("efa_rdma_write_recv_bytes")
	m.data.SetDescription("The number of bytes received by RDMA write operations")
	m.data.SetUnit("By")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
}

func (m *metricEfaRdmaWriteRecvBytes) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricEfaRdmaWriteRecvBytes) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricEfaRdmaWriteRecvBytes) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricEfaRdmaWriteRecvBytes(cfg MetricConfig) metricEfaRdmaWriteRecvBytes {
	m := metricEfaRdmaWriteRecvBytes{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricEfaRetransBytes struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills efa_retrans_bytes metric with initial data.
func (m *metricEfaRetransBytes) init() {
	m.data.SetName("efa_retrans_bytes")
	m.data.SetDescription("The number of EFA SRD bytes retransmitted")
	m.data.SetUnit("By")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
}

func (m *metricEfaRetransBytes) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricEfaRetransBytes) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricEfaRetransBytes) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricEfaRetransBytes(cfg MetricConfig) metricEfaRetransBytes {
	m := metricEfaRetransBytes{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricEfaRetransPkts struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills efa_retrans_pkts metric with initial data.
func (m *metricEfaRetransPkts) init() {
	m.data.SetName("efa_retrans_pkts")
	m.data.SetDescription("The number of EFA SRD packets retransmitted")
	m.data.SetUnit("1")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
}

func (m *metricEfaRetransPkts) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricEfaRetransPkts) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricEfaRetransPkts) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricEfaRetransPkts(cfg MetricConfig) metricEfaRetransPkts {
	m := metricEfaRetransPkts{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricEfaRetransTimeoutEvents struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills efa_retrans_timeout_events metric with initial data.
func (m *metricEfaRetransTimeoutEvents) init() {
	m.data.SetName("efa_retrans_timeout_events")
	m.data.SetDescription("The number of times EFA SRD traffic timed out and resulted in a network path change")
	m.data.SetUnit("1")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
}

func (m *metricEfaRetransTimeoutEvents) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricEfaRetransTimeoutEvents) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricEfaRetransTimeoutEvents) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricEfaRetransTimeoutEvents(cfg MetricConfig) metricEfaRetransTimeoutEvents {
	m := metricEfaRetransTimeoutEvents{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricEfaRxBytes struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills efa_rx_bytes metric with initial data.
func (m *metricEfaRxBytes) init() {
	m.data.SetName("efa_rx_bytes")
	m.data.SetDescription("The number of bytes received")
	m.data.SetUnit("By")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
}

func (m *metricEfaRxBytes) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricEfaRxBytes) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricEfaRxBytes) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricEfaRxBytes(cfg MetricConfig) metricEfaRxBytes {
	m := metricEfaRxBytes{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricEfaRxDropped struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills efa_rx_dropped metric with initial data.
func (m *metricEfaRxDropped) init() {
	m.data.SetName("efa_rx_dropped")
	m.data.SetDescription("The number of packets that were received and then dropped")
	m.data.SetUnit("1")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
}

func (m *metricEfaRxDropped) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricEfaRxDropped) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricEfaRxDropped) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricEfaRxDropped(cfg MetricConfig) metricEfaRxDropped {
	m := metricEfaRxDropped{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricEfaTxBytes struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills efa_tx_bytes metric with initial data.
func (m *metricEfaTxBytes) init() {
	m.data.SetName("efa_tx_bytes")
	m.data.SetDescription("The number of bytes transmitted")
	m.data.SetUnit("By")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
}

func (m *metricEfaTxBytes) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricEfaTxBytes) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricEfaTxBytes) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricEfaTxBytes(cfg MetricConfig) metricEfaTxBytes {
	m := metricEfaTxBytes{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricEfaUnresponsiveRemoteEvents struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills efa_unresponsive_remote_events metric with initial data.
func (m *metricEfaUnresponsiveRemoteEvents) init() {
	m.data.SetName("efa_unresponsive_remote_events")
	m.data.SetDescription("The number of times an EFA SRD remote connection was unresponsive")
	m.data.SetUnit("1")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
}

func (m *metricEfaUnresponsiveRemoteEvents) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricEfaUnresponsiveRemoteEvents) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricEfaUnresponsiveRemoteEvents) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricEfaUnresponsiveRemoteEvents(cfg MetricConfig) metricEfaUnresponsiveRemoteEvents {
	m := metricEfaUnresponsiveRemoteEvents{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

// MetricsBuilder provides an interface for scrapers to report metrics while taking care of all the transformations
// required to produce metric representation defined in metadata and user config.
type MetricsBuilder struct {
	config                            MetricsBuilderConfig // config of the metrics builder.
	startTime                         pcommon.Timestamp    // start time that will be applied to all recorded data points.
	metricsCapacity                   int                  // maximum observed number of metrics per resource.
	metricsBuffer                     pmetric.Metrics      // accumulates metrics data before emitting.
	buildInfo                         component.BuildInfo  // contains version information.
	resourceAttributeIncludeFilter    map[string]filter.Filter
	resourceAttributeExcludeFilter    map[string]filter.Filter
	metricEfaImpairedRemoteConnEvents metricEfaImpairedRemoteConnEvents
	metricEfaRdmaReadBytes            metricEfaRdmaReadBytes
	metricEfaRdmaWriteBytes           metricEfaRdmaWriteBytes
	metricEfaRdmaWriteRecvBytes       metricEfaRdmaWriteRecvBytes
	metricEfaRetransBytes             metricEfaRetransBytes
	metricEfaRetransPkts              metricEfaRetransPkts
	metricEfaRetransTimeoutEvents     metricEfaRetransTimeoutEvents
	metricEfaRxBytes                  metricEfaRxBytes
	metricEfaRxDropped                metricEfaRxDropped
	metricEfaTxBytes                  metricEfaTxBytes
	metricEfaUnresponsiveRemoteEvents metricEfaUnresponsiveRemoteEvents
}

// MetricBuilderOption applies changes to default metrics builder.
type MetricBuilderOption interface {
	apply(*MetricsBuilder)
}

type metricBuilderOptionFunc func(mb *MetricsBuilder)

func (mbof metricBuilderOptionFunc) apply(mb *MetricsBuilder) {
	mbof(mb)
}

// WithStartTime sets startTime on the metrics builder.
func WithStartTime(startTime pcommon.Timestamp) MetricBuilderOption {
	return metricBuilderOptionFunc(func(mb *MetricsBuilder) {
		mb.startTime = startTime
	})
}
func NewMetricsBuilder(mbc MetricsBuilderConfig, settings receiver.Settings, options ...MetricBuilderOption) *MetricsBuilder {
	mb := &MetricsBuilder{
		config:                            mbc,
		startTime:                         pcommon.NewTimestampFromTime(time.Now()),
		metricsBuffer:                     pmetric.NewMetrics(),
		buildInfo:                         settings.BuildInfo,
		metricEfaImpairedRemoteConnEvents: newMetricEfaImpairedRemoteConnEvents(mbc.Metrics.EfaImpairedRemoteConnEvents),
		metricEfaRdmaReadBytes:            newMetricEfaRdmaReadBytes(mbc.Metrics.EfaRdmaReadBytes),
		metricEfaRdmaWriteBytes:           newMetricEfaRdmaWriteBytes(mbc.Metrics.EfaRdmaWriteBytes),
		metricEfaRdmaWriteRecvBytes:       newMetricEfaRdmaWriteRecvBytes(mbc.Metrics.EfaRdmaWriteRecvBytes),
		metricEfaRetransBytes:             newMetricEfaRetransBytes(mbc.Metrics.EfaRetransBytes),
		metricEfaRetransPkts:              newMetricEfaRetransPkts(mbc.Metrics.EfaRetransPkts),
		metricEfaRetransTimeoutEvents:     newMetricEfaRetransTimeoutEvents(mbc.Metrics.EfaRetransTimeoutEvents),
		metricEfaRxBytes:                  newMetricEfaRxBytes(mbc.Metrics.EfaRxBytes),
		metricEfaRxDropped:                newMetricEfaRxDropped(mbc.Metrics.EfaRxDropped),
		metricEfaTxBytes:                  newMetricEfaTxBytes(mbc.Metrics.EfaTxBytes),
		metricEfaUnresponsiveRemoteEvents: newMetricEfaUnresponsiveRemoteEvents(mbc.Metrics.EfaUnresponsiveRemoteEvents),
		resourceAttributeIncludeFilter:    make(map[string]filter.Filter),
		resourceAttributeExcludeFilter:    make(map[string]filter.Filter),
	}
	if mbc.ResourceAttributes.Device.MetricsInclude != nil {
		mb.resourceAttributeIncludeFilter["device"] = filter.CreateFilter(mbc.ResourceAttributes.Device.MetricsInclude)
	}
	if mbc.ResourceAttributes.Device.MetricsExclude != nil {
		mb.resourceAttributeExcludeFilter["device"] = filter.CreateFilter(mbc.ResourceAttributes.Device.MetricsExclude)
	}
	if mbc.ResourceAttributes.Port.MetricsInclude != nil {
		mb.resourceAttributeIncludeFilter["port"] = filter.CreateFilter(mbc.ResourceAttributes.Port.MetricsInclude)
	}
	if mbc.ResourceAttributes.Port.MetricsExclude != nil {
		mb.resourceAttributeExcludeFilter["port"] = filter.CreateFilter(mbc.ResourceAttributes.Port.MetricsExclude)
	}

	for _, op := range options {
		op.apply(mb)
	}
	return mb
}

// NewResourceBuilder returns a new resource builder that should be used to build a resource associated with for the emitted metrics.
func (mb *MetricsBuilder) NewResourceBuilder() *ResourceBuilder {
	return NewResourceBuilder(mb.config.ResourceAttributes)
}

// updateCapacity updates max length of metrics and resource attributes that will be used for the slice capacity.
func (mb *MetricsBuilder) updateCapacity(rm pmetric.ResourceMetrics) {
	if mb.metricsCapacity < rm.ScopeMetrics().At(0).Metrics().Len() {
		mb.metricsCapacity = rm.ScopeMetrics().At(0).Metrics().Len()
	}
}

// ResourceMetricsOption applies changes to provided resource metrics.
type ResourceMetricsOption interface {
	apply(pmetric.ResourceMetrics)
}

type resourceMetricsOptionFunc func(pmetric.ResourceMetrics)

func (rmof resourceMetricsOptionFunc) apply(rm pmetric.ResourceMetrics) {
	rmof(rm)
}

// WithResource sets the provided resource on the emitted ResourceMetrics.
// It's recommended to use ResourceBuilder to create the resource.
func WithResource(res pcommon.Resource) ResourceMetricsOption {
	return resourceMetricsOptionFunc(func(rm pmetric.ResourceMetrics) {
		res.CopyTo(rm.Resource())
	})
}

// WithStartTimeOverride overrides start time for all the resource metrics data points.
// This option should be only used if different start time has to be set on metrics coming from different resources.
func WithStartTimeOverride(start pcommon.Timestamp) ResourceMetricsOption {
	return resourceMetricsOptionFunc(func(rm pmetric.ResourceMetrics) {
		var dps pmetric.NumberDataPointSlice
		metrics := rm.ScopeMetrics().At(0).Metrics()
		for i := 0; i < metrics.Len(); i++ {
			switch metrics.At(i).Type() {
			case pmetric.MetricTypeGauge:
				dps = metrics.At(i).Gauge().DataPoints()
			case pmetric.MetricTypeSum:
				dps = metrics.At(i).Sum().DataPoints()
			}
			for j := 0; j < dps.Len(); j++ {
				dps.At(j).SetStartTimestamp(start)
			}
		}
	})
}

// EmitForResource saves all the generated metrics under a new resource and updates the internal state to be ready for
// recording another set of data points as part of another resource. This function can be helpful when one scraper
// needs to emit metrics from several resources. Otherwise calling this function is not required,
// just `Emit` function can be called instead.
// Resource attributes should be provided as ResourceMetricsOption arguments.
func (mb *MetricsBuilder) EmitForResource(options ...ResourceMetricsOption) {
	rm := pmetric.NewResourceMetrics()
	ils := rm.ScopeMetrics().AppendEmpty()
	ils.Scope().SetName(ScopeName)
	ils.Scope().SetVersion(mb.buildInfo.Version)
	ils.Metrics().EnsureCapacity(mb.metricsCapacity)
	mb.metricEfaImpairedRemoteConnEvents.emit(ils.Metrics())
	mb.metricEfaRdmaReadBytes.emit(ils.Metrics())
	mb.metricEfaRdmaWriteBytes.emit(ils.Metrics())
	mb.metricEfaRdmaWriteRecvBytes.emit(ils.Metrics())
	mb.metricEfaRetransBytes.emit(ils.Metrics())
	mb.metricEfaRetransPkts.emit(ils.Metrics())
	mb.metricEfaRetransTimeoutEvents.emit(ils.Metrics())
	mb.metricEfaRxBytes.emit(ils.Metrics())
	mb.metricEfaRxDropped.emit(ils.Metrics())
	mb.metricEfaTxBytes.emit(ils.Metrics())
	mb.metricEfaUnresponsiveRemoteEvents.emit(ils.Metrics())

	for _, op := range options {
		op.apply(rm)
	}
	for attr, filter := range mb.resourceAttributeIncludeFilter {
		if val, ok := rm.Resource().Attributes().Get(attr); ok && !filter.Matches(val.AsString()) {
			return
		}
	}
	for attr, filter := range mb.resourceAttributeExcludeFilter {
		if val, ok := rm.Resource().Attributes().Get(attr); ok && filter.Matches(val.AsString()) {
			return
		}
	}

	if ils.Metrics().Len() > 0 {
		mb.updateCapacity(rm)
		rm.MoveTo(mb.metricsBuffer.ResourceMetrics().AppendEmpty())
	}
}

// Emit returns all the metrics accumulated by the metrics builder and updates the internal state to be ready for
// recording another set of metrics. This function will be responsible for applying all the transformations required to
// produce metric representation defined in metadata and user config, e.g. delta or cumulative.
func (mb *MetricsBuilder) Emit(options ...ResourceMetricsOption) pmetric.Metrics {
	mb.EmitForResource(options...)
	metrics := mb.metricsBuffer
	mb.metricsBuffer = pmetric.NewMetrics()
	return metrics
}

// RecordEfaImpairedRemoteConnEventsDataPoint adds a data point to efa_impaired_remote_conn_events metric.
func (mb *MetricsBuilder) RecordEfaImpairedRemoteConnEventsDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricEfaImpairedRemoteConnEvents.recordDataPoint(mb.startTime, ts, val)
}

// RecordEfaRdmaReadBytesDataPoint adds a data point to efa_rdma_read_bytes metric.
func (mb *MetricsBuilder) RecordEfaRdmaReadBytesDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricEfaRdmaReadBytes.recordDataPoint(mb.startTime, ts, val)
}

// RecordEfaRdmaWriteBytesDataPoint adds a data point to efa_rdma_write_bytes metric.
func (mb *MetricsBuilder) RecordEfaRdmaWriteBytesDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricEfaRdmaWriteBytes.recordDataPoint(mb.startTime, ts, val)
}

// RecordEfaRdmaWriteRecvBytesDataPoint adds a data point to efa_rdma_write_recv_bytes metric.
func (mb *MetricsBuilder) RecordEfaRdmaWriteRecvBytesDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricEfaRdmaWriteRecvBytes.recordDataPoint(mb.startTime, ts, val)
}

// RecordEfaRetransBytesDataPoint adds a data point to efa_retrans_bytes metric.
func (mb *MetricsBuilder) RecordEfaRetransBytesDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricEfaRetransBytes.recordDataPoint(mb.startTime, ts, val)
}

// RecordEfaRetransPktsDataPoint adds a data point to efa_retrans_pkts metric.
func (mb *MetricsBuilder) RecordEfaRetransPktsDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricEfaRetransPkts.recordDataPoint(mb.startTime, ts, val)
}

// RecordEfaRetransTimeoutEventsDataPoint adds a data point to efa_retrans_timeout_events metric.
func (mb *MetricsBuilder) RecordEfaRetransTimeoutEventsDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricEfaRetransTimeoutEvents.recordDataPoint(mb.startTime, ts, val)
}

// RecordEfaRxBytesDataPoint adds a data point to efa_rx_bytes metric.
func (mb *MetricsBuilder) RecordEfaRxBytesDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricEfaRxBytes.recordDataPoint(mb.startTime, ts, val)
}

// RecordEfaRxDroppedDataPoint adds a data point to efa_rx_dropped metric.
func (mb *MetricsBuilder) RecordEfaRxDroppedDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricEfaRxDropped.recordDataPoint(mb.startTime, ts, val)
}

// RecordEfaTxBytesDataPoint adds a data point to efa_tx_bytes metric.
func (mb *MetricsBuilder) RecordEfaTxBytesDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricEfaTxBytes.recordDataPoint(mb.startTime, ts, val)
}

// RecordEfaUnresponsiveRemoteEventsDataPoint adds a data point to efa_unresponsive_remote_events metric.
func (mb *MetricsBuilder) RecordEfaUnresponsiveRemoteEventsDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricEfaUnresponsiveRemoteEvents.recordDataPoint(mb.startTime, ts, val)
}

// Reset resets metrics builder to its initial state. It should be used when external metrics source is restarted,
// and metrics builder should update its startTime and reset it's internal state accordingly.
func (mb *MetricsBuilder) Reset(options ...MetricBuilderOption) {
	mb.startTime = pcommon.NewTimestampFromTime(time.Now())
	for _, op := range options {
		op.apply(mb)
	}
}
