// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/filter"
)

// MetricConfig provides common config for a particular metric.
type MetricConfig struct {
	Enabled bool `mapstructure:"enabled"`

	enabledSetByUser bool
}

func (ms *MetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}
	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// MetricsConfig provides config for awsefareceiver metrics.
type MetricsConfig struct {
	EfaImpairedRemoteConnEvents MetricConfig `mapstructure:"efa_impaired_remote_conn_events"`
	EfaRdmaReadBytes            MetricConfig `mapstructure:"efa_rdma_read_bytes"`
	EfaRdmaWriteBytes           MetricConfig `mapstructure:"efa_rdma_write_bytes"`
	EfaRdmaWriteRecvBytes       MetricConfig `mapstructure:"efa_rdma_write_recv_bytes"`
	EfaRetransBytes             MetricConfig `mapstructure:"efa_retrans_bytes"`
	EfaRetransPkts              MetricConfig `mapstructure:"efa_retrans_pkts"`
	EfaRetransTimeoutEvents     MetricConfig `mapstructure:"efa_retrans_timeout_events"`
	EfaRxBytes                  MetricConfig `mapstructure:"efa_rx_bytes"`
	EfaRxDropped                MetricConfig `mapstructure:"efa_rx_dropped"`
	EfaTxBytes                  MetricConfig `mapstructure:"efa_tx_bytes"`
	EfaUnresponsiveRemoteEvents MetricConfig `mapstructure:"efa_unresponsive_remote_events"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		EfaImpairedRemoteConnEvents: MetricConfig{
			Enabled: true,
		},
		EfaRdmaReadBytes: MetricConfig{
			Enabled: true,
		},
		EfaRdmaWriteBytes: MetricConfig{
			Enabled: true,
		},
		EfaRdmaWriteRecvBytes: MetricConfig{
			Enabled: true,
		},
		EfaRetransBytes: MetricConfig{
			Enabled: true,
		},
		EfaRetransPkts: MetricConfig{
			Enabled: true,
		},
		EfaRetransTimeoutEvents: MetricConfig{
			Enabled: true,
		},
		EfaRxBytes: MetricConfig{
			Enabled: true,
		},
		EfaRxDropped: MetricConfig{
			Enabled: true,
		},
		EfaTxBytes: MetricConfig{
			Enabled: true,
		},
		EfaUnresponsiveRemoteEvents: MetricConfig{
			Enabled: true,
		},
	}
}

// ResourceAttributeConfig provides common config for a particular resource attribute.
type ResourceAttributeConfig struct {
	Enabled bool `mapstructure:"enabled"`
	// Experimental: MetricsInclude defines a list of filters for attribute values.
	// If the list is not empty, only metrics with matching resource attribute values will be emitted.
	MetricsInclude []filter.Config `mapstructure:"metrics_include"`
	// Experimental: MetricsExclude defines a list of filters for attribute values.
	// If the list is not empty, metrics with matching resource attribute values will not be emitted.
	// MetricsInclude has higher priority than MetricsExclude.
	MetricsExclude []filter.Config `mapstructure:"metrics_exclude"`

	enabledSetByUser bool
}

func (rac *ResourceAttributeConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(rac)
	if err != nil {
		return err
	}
	rac.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// ResourceAttributesConfig provides config for awsefareceiver resource attributes.
type ResourceAttributesConfig struct {
	Device ResourceAttributeConfig `mapstructure:"device"`
	Port   ResourceAttributeConfig `mapstructure:"port"`
}

func DefaultResourceAttributesConfig() ResourceAttributesConfig {
	return ResourceAttributesConfig{
		Device: ResourceAttributeConfig{
			Enabled: true,
		},
		Port: ResourceAttributeConfig{
			Enabled: true,
		},
	}
}

// MetricsBuilderConfig is a configuration for awsefareceiver metrics builder.
type MetricsBuilderConfig struct {
	Metrics            MetricsConfig            `mapstructure:"metrics"`
	ResourceAttributes ResourceAttributesConfig `mapstructure:"resource_attributes"`
}

func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics:            DefaultMetricsConfig(),
		ResourceAttributes: DefaultResourceAttributesConfig(),
	}
}
