// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/pdata/pcommon"
)

// ResourceBuilder is a helper struct to build resources predefined in metadata.yaml.
// The ResourceBuilder is not thread-safe and must not to be used in multiple goroutines.
type ResourceBuilder struct {
	config ResourceAttributesConfig
	res    pcommon.Resource
}

// NewResourceBuilder creates a new ResourceBuilder. This method should be called on the start of the application.
func NewResourceBuilder(rac ResourceAttributesConfig) *ResourceBuilder {
	return &ResourceBuilder{
		config: rac,
		res:    pcommon.NewResource(),
	}
}

// SetDevice sets provided value as "device" attribute.
func (rb *ResourceBuilder) SetDevice(val string) {
	if rb.config.Device.Enabled {
		rb.res.Attributes().PutStr("device", val)
	}
}

// SetPort sets provided value as "port" attribute.
func (rb *ResourceBuilder) SetPort(val string) {
	if rb.config.Port.Enabled {
		rb.res.Attributes().PutStr("port", val)
	}
}

// SetPod sets provided value as "pod" attribute.
func (rb *ResourceBuilder) SetPod(val string) {
	if rb.config.Pod.Enabled {
		rb.res.Attributes().PutStr("pod", val)
	}
}

// SetNamespace sets provided value as "namespace" attribute.
func (rb *ResourceBuilder) SetNamespace(val string) {
	if rb.config.Namespace.Enabled {
		rb.res.Attributes().PutStr("namespace", val)
	}
}

// SetContainer sets provided value as "container" attribute.
func (rb *ResourceBuilder) SetContainer(val string) {
	if rb.config.Container.Enabled {
		rb.res.Attributes().PutStr("container", val)
	}
}

// Emit returns the built resource and resets the internal builder state.
func (rb *ResourceBuilder) Emit() pcommon.Resource {
	r := rb.res
	rb.res = pcommon.NewResource()
	return r
}
