// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/confmap"
	"go.opentelemetry.io/collector/filter"
)

// MetricConfig provides common config for a particular metric.
type MetricConfig struct {
	Enabled bool `mapstructure:"enabled"`

	enabledSetByUser bool
}

func (ms *MetricConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(ms)
	if err != nil {
		return err
	}
	ms.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// MetricsConfig provides config for awsefareceiver metrics.
type MetricsConfig struct {
	NodeEfaImpairedRemoteConnEvents  MetricConfig `mapstructure:"node_efa_impaired_remote_conn_events"`
	NodeEfaRdmaReadBytes             MetricConfig `mapstructure:"node_efa_rdma_read_bytes"`
	NodeEfaRdmaWriteBytes            MetricConfig `mapstructure:"node_efa_rdma_write_bytes"`
	NodeEfaRdmaWriteRecvBytes        MetricConfig `mapstructure:"node_efa_rdma_write_recv_bytes"`
	NodeEfaRetransBytes              MetricConfig `mapstructure:"node_efa_retrans_bytes"`
	NodeEfaRetransPkts               MetricConfig `mapstructure:"node_efa_retrans_pkts"`
	NodeEfaRetransTimeoutEvents      MetricConfig `mapstructure:"node_efa_retrans_timeout_events"`
	NodeEfaRxBytes                   MetricConfig `mapstructure:"node_efa_rx_bytes"`
	NodeEfaRxDropped                 MetricConfig `mapstructure:"node_efa_rx_dropped"`
	NodeEfaTxBytes                   MetricConfig `mapstructure:"node_efa_tx_bytes"`
	NodeEfaUnresponsiveRemoteEvents  MetricConfig `mapstructure:"node_efa_unresponsive_remote_events"`
}

func DefaultMetricsConfig() MetricsConfig {
	return MetricsConfig{
		NodeEfaImpairedRemoteConnEvents:  MetricConfig{Enabled: true},
		NodeEfaRdmaReadBytes:             MetricConfig{Enabled: true},
		NodeEfaRdmaWriteBytes:            MetricConfig{Enabled: true},
		NodeEfaRdmaWriteRecvBytes:        MetricConfig{Enabled: true},
		NodeEfaRetransBytes:              MetricConfig{Enabled: true},
		NodeEfaRetransPkts:               MetricConfig{Enabled: true},
		NodeEfaRetransTimeoutEvents:      MetricConfig{Enabled: true},
		NodeEfaRxBytes:                   MetricConfig{Enabled: true},
		NodeEfaRxDropped:                 MetricConfig{Enabled: true},
		NodeEfaTxBytes:                   MetricConfig{Enabled: true},
		NodeEfaUnresponsiveRemoteEvents:  MetricConfig{Enabled: true},
	}
}

// ResourceAttributeConfig provides common config for a particular resource attribute.
type ResourceAttributeConfig struct {
	Enabled bool `mapstructure:"enabled"`

	MetricsInclude []filter.Config `mapstructure:"metrics_include"`
	MetricsExclude []filter.Config `mapstructure:"metrics_exclude"`

	enabledSetByUser bool
}

func (rac *ResourceAttributeConfig) Unmarshal(parser *confmap.Conf) error {
	if parser == nil {
		return nil
	}
	err := parser.Unmarshal(rac)
	if err != nil {
		return err
	}
	rac.enabledSetByUser = parser.IsSet("enabled")
	return nil
}

// ResourceAttributesConfig provides config for awsefareceiver resource attributes.
type ResourceAttributesConfig struct {
	Device ResourceAttributeConfig `mapstructure:"device"`
	Port   ResourceAttributeConfig `mapstructure:"port"`
}

func DefaultResourceAttributesConfig() ResourceAttributesConfig {
	return ResourceAttributesConfig{
		Device: ResourceAttributeConfig{Enabled: true},
		Port:   ResourceAttributeConfig{Enabled: true},
	}
}

// MetricsBuilderConfig is a configuration for awsefareceiver metrics builder.
type MetricsBuilderConfig struct {
	Metrics            MetricsConfig            `mapstructure:"metrics"`
	ResourceAttributes ResourceAttributesConfig `mapstructure:"resource_attributes"`
}

func DefaultMetricsBuilderConfig() MetricsBuilderConfig {
	return MetricsBuilderConfig{
		Metrics:            DefaultMetricsConfig(),
		ResourceAttributes: DefaultResourceAttributesConfig(),
	}
}
