// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"time"

	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/collector/filter"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.opentelemetry.io/collector/receiver"
)

var MetricsInfo = metricsInfo{
	NodeEfaImpairedRemoteConnEvents: metricInfo{
		Name: "node_efa_impaired_remote_conn_events",
	},
	NodeEfaRdmaReadBytes: metricInfo{
		Name: "node_efa_rdma_read_bytes",
	},
	NodeEfaRdmaWriteBytes: metricInfo{
		Name: "node_efa_rdma_write_bytes",
	},
	NodeEfaRdmaWriteRecvBytes: metricInfo{
		Name: "node_efa_rdma_write_recv_bytes",
	},
	NodeEfaRetransBytes: metricInfo{
		Name: "node_efa_retrans_bytes",
	},
	NodeEfaRetransPkts: metricInfo{
		Name: "node_efa_retrans_pkts",
	},
	NodeEfaRetransTimeoutEvents: metricInfo{
		Name: "node_efa_retrans_timeout_events",
	},
	NodeEfaRxBytes: metricInfo{
		Name: "node_efa_rx_bytes",
	},
	NodeEfaRxDropped: metricInfo{
		Name: "node_efa_rx_dropped",
	},
	NodeEfaTxBytes: metricInfo{
		Name: "node_efa_tx_bytes",
	},
	NodeEfaUnresponsiveRemoteEvents: metricInfo{
		Name: "node_efa_unresponsive_remote_events",
	},
}

type metricsInfo struct {
	NodeEfaImpairedRemoteConnEvents metricInfo
	NodeEfaRdmaReadBytes            metricInfo
	NodeEfaRdmaWriteBytes           metricInfo
	NodeEfaRdmaWriteRecvBytes       metricInfo
	NodeEfaRetransBytes             metricInfo
	NodeEfaRetransPkts              metricInfo
	NodeEfaRetransTimeoutEvents     metricInfo
	NodeEfaRxBytes                  metricInfo
	NodeEfaRxDropped                metricInfo
	NodeEfaTxBytes                  metricInfo
	NodeEfaUnresponsiveRemoteEvents metricInfo
}

type metricInfo struct {
	Name string
}

type metricNodeEfaImpairedRemoteConnEvents struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills node_efa_impaired_remote_conn_events metric with initial data.
func (m *metricNodeEfaImpairedRemoteConnEvents) init() {
	m.data.SetName("node_efa_impaired_remote_conn_events")
	m.data.SetDescription("The number of times EFA SRD connections entered an impaired state resulting in a reduced throughput rate limit")
	m.data.SetUnit("1")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
}

func (m *metricNodeEfaImpairedRemoteConnEvents) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNodeEfaImpairedRemoteConnEvents) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNodeEfaImpairedRemoteConnEvents) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNodeEfaImpairedRemoteConnEvents(cfg MetricConfig) metricNodeEfaImpairedRemoteConnEvents {
	m := metricNodeEfaImpairedRemoteConnEvents{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNodeEfaRdmaReadBytes struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills node_efa_rdma_read_bytes metric with initial data.
func (m *metricNodeEfaRdmaReadBytes) init() {
	m.data.SetName("node_efa_rdma_read_bytes")
	m.data.SetDescription("The number of bytes received using RDMA read operations")
	m.data.SetUnit("By")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
}

func (m *metricNodeEfaRdmaReadBytes) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNodeEfaRdmaReadBytes) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNodeEfaRdmaReadBytes) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNodeEfaRdmaReadBytes(cfg MetricConfig) metricNodeEfaRdmaReadBytes {
	m := metricNodeEfaRdmaReadBytes{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNodeEfaRdmaWriteBytes struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills node_efa_rdma_write_bytes metric with initial data.
func (m *metricNodeEfaRdmaWriteBytes) init() {
	m.data.SetName("node_efa_rdma_write_bytes")
	m.data.SetDescription("The number of bytes written by other instances using RDMA write operations")
	m.data.SetUnit("By")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
}

func (m *metricNodeEfaRdmaWriteBytes) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNodeEfaRdmaWriteBytes) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNodeEfaRdmaWriteBytes) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNodeEfaRdmaWriteBytes(cfg MetricConfig) metricNodeEfaRdmaWriteBytes {
	m := metricNodeEfaRdmaWriteBytes{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNodeEfaRdmaWriteRecvBytes struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills node_efa_rdma_write_recv_bytes metric with initial data.
func (m *metricNodeEfaRdmaWriteRecvBytes) init() {
	m.data.SetName("node_efa_rdma_write_recv_bytes")
	m.data.SetDescription("The number of bytes received by RDMA write operations")
	m.data.SetUnit("By")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
}

func (m *metricNodeEfaRdmaWriteRecvBytes) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNodeEfaRdmaWriteRecvBytes) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNodeEfaRdmaWriteRecvBytes) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNodeEfaRdmaWriteRecvBytes(cfg MetricConfig) metricNodeEfaRdmaWriteRecvBytes {
	m := metricNodeEfaRdmaWriteRecvBytes{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNodeEfaRetransBytes struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills node_efa_retrans_bytes metric with initial data.
func (m *metricNodeEfaRetransBytes) init() {
	m.data.SetName("node_efa_retrans_bytes")
	m.data.SetDescription("The number of EFA SRD bytes retransmitted")
	m.data.SetUnit("By")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
}

func (m *metricNodeEfaRetransBytes) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNodeEfaRetransBytes) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNodeEfaRetransBytes) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNodeEfaRetransBytes(cfg MetricConfig) metricNodeEfaRetransBytes {
	m := metricNodeEfaRetransBytes{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNodeEfaRetransPkts struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills node_efa_retrans_pkts metric with initial data.
func (m *metricNodeEfaRetransPkts) init() {
	m.data.SetName("node_efa_retrans_pkts")
	m.data.SetDescription("The number of EFA SRD packets retransmitted")
	m.data.SetUnit("1")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
}

func (m *metricNodeEfaRetransPkts) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNodeEfaRetransPkts) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNodeEfaRetransPkts) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNodeEfaRetransPkts(cfg MetricConfig) metricNodeEfaRetransPkts {
	m := metricNodeEfaRetransPkts{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNodeEfaRetransTimeoutEvents struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills node_efa_retrans_timeout_events metric with initial data.
func (m *metricNodeEfaRetransTimeoutEvents) init() {
	m.data.SetName("node_efa_retrans_timeout_events")
	m.data.SetDescription("The number of times EFA SRD traffic timed out and resulted in a network path change")
	m.data.SetUnit("1")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
}

func (m *metricNodeEfaRetransTimeoutEvents) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNodeEfaRetransTimeoutEvents) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNodeEfaRetransTimeoutEvents) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNodeEfaRetransTimeoutEvents(cfg MetricConfig) metricNodeEfaRetransTimeoutEvents {
	m := metricNodeEfaRetransTimeoutEvents{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNodeEfaRxBytes struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills node_efa_rx_bytes metric with initial data.
func (m *metricNodeEfaRxBytes) init() {
	m.data.SetName("node_efa_rx_bytes")
	m.data.SetDescription("The number of bytes received")
	m.data.SetUnit("By")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
}

func (m *metricNodeEfaRxBytes) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNodeEfaRxBytes) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNodeEfaRxBytes) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNodeEfaRxBytes(cfg MetricConfig) metricNodeEfaRxBytes {
	m := metricNodeEfaRxBytes{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNodeEfaRxDropped struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills node_efa_rx_dropped metric with initial data.
func (m *metricNodeEfaRxDropped) init() {
	m.data.SetName("node_efa_rx_dropped")
	m.data.SetDescription("The number of packets that were received and then dropped")
	m.data.SetUnit("1")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
}

func (m *metricNodeEfaRxDropped) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNodeEfaRxDropped) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNodeEfaRxDropped) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNodeEfaRxDropped(cfg MetricConfig) metricNodeEfaRxDropped {
	m := metricNodeEfaRxDropped{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNodeEfaTxBytes struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills node_efa_tx_bytes metric with initial data.
func (m *metricNodeEfaTxBytes) init() {
	m.data.SetName("node_efa_tx_bytes")
	m.data.SetDescription("The number of bytes transmitted")
	m.data.SetUnit("By")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
}

func (m *metricNodeEfaTxBytes) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNodeEfaTxBytes) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNodeEfaTxBytes) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNodeEfaTxBytes(cfg MetricConfig) metricNodeEfaTxBytes {
	m := metricNodeEfaTxBytes{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricNodeEfaUnresponsiveRemoteEvents struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills node_efa_unresponsive_remote_events metric with initial data.
func (m *metricNodeEfaUnresponsiveRemoteEvents) init() {
	m.data.SetName("node_efa_unresponsive_remote_events")
	m.data.SetDescription("The number of times an EFA SRD remote connection was unresponsive")
	m.data.SetUnit("1")
	m.data.SetEmptySum()
	m.data.Sum().SetIsMonotonic(true)
	m.data.Sum().SetAggregationTemporality(pmetric.AggregationTemporalityCumulative)
}

func (m *metricNodeEfaUnresponsiveRemoteEvents) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Sum().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricNodeEfaUnresponsiveRemoteEvents) updateCapacity() {
	if m.data.Sum().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Sum().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricNodeEfaUnresponsiveRemoteEvents) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Sum().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricNodeEfaUnresponsiveRemoteEvents(cfg MetricConfig) metricNodeEfaUnresponsiveRemoteEvents {
	m := metricNodeEfaUnresponsiveRemoteEvents{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

// MetricsBuilder provides an interface for scrapers to report metrics while taking care of all the transformations
// required to produce metric representation defined in metadata and user config.
type MetricsBuilder struct {
	config                                MetricsBuilderConfig // config of the metrics builder.
	startTime                             pcommon.Timestamp    // start time that will be applied to all recorded data points.
	metricsCapacity                       int                  // maximum observed number of metrics per resource.
	metricsBuffer                         pmetric.Metrics      // accumulates metrics data before emitting.
	buildInfo                             component.BuildInfo  // contains version information.
	resourceAttributeIncludeFilter        map[string]filter.Filter
	resourceAttributeExcludeFilter        map[string]filter.Filter
	metricNodeEfaImpairedRemoteConnEvents metricNodeEfaImpairedRemoteConnEvents
	metricNodeEfaRdmaReadBytes            metricNodeEfaRdmaReadBytes
	metricNodeEfaRdmaWriteBytes           metricNodeEfaRdmaWriteBytes
	metricNodeEfaRdmaWriteRecvBytes       metricNodeEfaRdmaWriteRecvBytes
	metricNodeEfaRetransBytes             metricNodeEfaRetransBytes
	metricNodeEfaRetransPkts              metricNodeEfaRetransPkts
	metricNodeEfaRetransTimeoutEvents     metricNodeEfaRetransTimeoutEvents
	metricNodeEfaRxBytes                  metricNodeEfaRxBytes
	metricNodeEfaRxDropped                metricNodeEfaRxDropped
	metricNodeEfaTxBytes                  metricNodeEfaTxBytes
	metricNodeEfaUnresponsiveRemoteEvents metricNodeEfaUnresponsiveRemoteEvents
}

// MetricBuilderOption applies changes to default metrics builder.
type MetricBuilderOption interface {
	apply(*MetricsBuilder)
}

type metricBuilderOptionFunc func(mb *MetricsBuilder)

func (mbof metricBuilderOptionFunc) apply(mb *MetricsBuilder) {
	mbof(mb)
}

// WithStartTime sets startTime on the metrics builder.
func WithStartTime(startTime pcommon.Timestamp) MetricBuilderOption {
	return metricBuilderOptionFunc(func(mb *MetricsBuilder) {
		mb.startTime = startTime
	})
}
func NewMetricsBuilder(mbc MetricsBuilderConfig, settings receiver.Settings, options ...MetricBuilderOption) *MetricsBuilder {
	mb := &MetricsBuilder{
		config:                                mbc,
		startTime:                             pcommon.NewTimestampFromTime(time.Now()),
		metricsBuffer:                         pmetric.NewMetrics(),
		buildInfo:                             settings.BuildInfo,
		metricNodeEfaImpairedRemoteConnEvents: newMetricNodeEfaImpairedRemoteConnEvents(mbc.Metrics.NodeEfaImpairedRemoteConnEvents),
		metricNodeEfaRdmaReadBytes:            newMetricNodeEfaRdmaReadBytes(mbc.Metrics.NodeEfaRdmaReadBytes),
		metricNodeEfaRdmaWriteBytes:           newMetricNodeEfaRdmaWriteBytes(mbc.Metrics.NodeEfaRdmaWriteBytes),
		metricNodeEfaRdmaWriteRecvBytes:       newMetricNodeEfaRdmaWriteRecvBytes(mbc.Metrics.NodeEfaRdmaWriteRecvBytes),
		metricNodeEfaRetransBytes:             newMetricNodeEfaRetransBytes(mbc.Metrics.NodeEfaRetransBytes),
		metricNodeEfaRetransPkts:              newMetricNodeEfaRetransPkts(mbc.Metrics.NodeEfaRetransPkts),
		metricNodeEfaRetransTimeoutEvents:     newMetricNodeEfaRetransTimeoutEvents(mbc.Metrics.NodeEfaRetransTimeoutEvents),
		metricNodeEfaRxBytes:                  newMetricNodeEfaRxBytes(mbc.Metrics.NodeEfaRxBytes),
		metricNodeEfaRxDropped:                newMetricNodeEfaRxDropped(mbc.Metrics.NodeEfaRxDropped),
		metricNodeEfaTxBytes:                  newMetricNodeEfaTxBytes(mbc.Metrics.NodeEfaTxBytes),
		metricNodeEfaUnresponsiveRemoteEvents: newMetricNodeEfaUnresponsiveRemoteEvents(mbc.Metrics.NodeEfaUnresponsiveRemoteEvents),
		resourceAttributeIncludeFilter:        make(map[string]filter.Filter),
		resourceAttributeExcludeFilter:        make(map[string]filter.Filter),
	}
	if mbc.ResourceAttributes.Device.MetricsInclude != nil {
		mb.resourceAttributeIncludeFilter["device"] = filter.CreateFilter(mbc.ResourceAttributes.Device.MetricsInclude)
	}
	if mbc.ResourceAttributes.Device.MetricsExclude != nil {
		mb.resourceAttributeExcludeFilter["device"] = filter.CreateFilter(mbc.ResourceAttributes.Device.MetricsExclude)
	}
	if mbc.ResourceAttributes.Port.MetricsInclude != nil {
		mb.resourceAttributeIncludeFilter["port"] = filter.CreateFilter(mbc.ResourceAttributes.Port.MetricsInclude)
	}
	if mbc.ResourceAttributes.Port.MetricsExclude != nil {
		mb.resourceAttributeExcludeFilter["port"] = filter.CreateFilter(mbc.ResourceAttributes.Port.MetricsExclude)
	}

	for _, op := range options {
		op.apply(mb)
	}
	return mb
}

// NewResourceBuilder returns a new resource builder that should be used to build a resource associated with for the emitted metrics.
func (mb *MetricsBuilder) NewResourceBuilder() *ResourceBuilder {
	return NewResourceBuilder(mb.config.ResourceAttributes)
}

// updateCapacity updates max length of metrics and resource attributes that will be used for the slice capacity.
func (mb *MetricsBuilder) updateCapacity(rm pmetric.ResourceMetrics) {
	if mb.metricsCapacity < rm.ScopeMetrics().At(0).Metrics().Len() {
		mb.metricsCapacity = rm.ScopeMetrics().At(0).Metrics().Len()
	}
}

// ResourceMetricsOption applies changes to provided resource metrics.
type ResourceMetricsOption interface {
	apply(pmetric.ResourceMetrics)
}

type resourceMetricsOptionFunc func(pmetric.ResourceMetrics)

func (rmof resourceMetricsOptionFunc) apply(rm pmetric.ResourceMetrics) {
	rmof(rm)
}

// WithResource sets the provided resource on the emitted ResourceMetrics.
// It's recommended to use ResourceBuilder to create the resource.
func WithResource(res pcommon.Resource) ResourceMetricsOption {
	return resourceMetricsOptionFunc(func(rm pmetric.ResourceMetrics) {
		res.CopyTo(rm.Resource())
	})
}

// WithStartTimeOverride overrides start time for all the resource metrics data points.
// This option should be only used if different start time has to be set on metrics coming from different resources.
func WithStartTimeOverride(start pcommon.Timestamp) ResourceMetricsOption {
	return resourceMetricsOptionFunc(func(rm pmetric.ResourceMetrics) {
		var dps pmetric.NumberDataPointSlice
		metrics := rm.ScopeMetrics().At(0).Metrics()
		for i := 0; i < metrics.Len(); i++ {
			switch metrics.At(i).Type() {
			case pmetric.MetricTypeGauge:
				dps = metrics.At(i).Gauge().DataPoints()
			case pmetric.MetricTypeSum:
				dps = metrics.At(i).Sum().DataPoints()
			}
			for j := 0; j < dps.Len(); j++ {
				dps.At(j).SetStartTimestamp(start)
			}
		}
	})
}

// EmitForResource saves all the generated metrics under a new resource and updates the internal state to be ready for
// recording another set of data points as part of another resource. This function can be helpful when one scraper
// needs to emit metrics from several resources. Otherwise calling this function is not required,
// just `Emit` function can be called instead.
// Resource attributes should be provided as ResourceMetricsOption arguments.
func (mb *MetricsBuilder) EmitForResource(options ...ResourceMetricsOption) {
	rm := pmetric.NewResourceMetrics()
	ils := rm.ScopeMetrics().AppendEmpty()
	ils.Scope().SetName(ScopeName)
	ils.Scope().SetVersion(mb.buildInfo.Version)
	ils.Metrics().EnsureCapacity(mb.metricsCapacity)
	mb.metricNodeEfaImpairedRemoteConnEvents.emit(ils.Metrics())
	mb.metricNodeEfaRdmaReadBytes.emit(ils.Metrics())
	mb.metricNodeEfaRdmaWriteBytes.emit(ils.Metrics())
	mb.metricNodeEfaRdmaWriteRecvBytes.emit(ils.Metrics())
	mb.metricNodeEfaRetransBytes.emit(ils.Metrics())
	mb.metricNodeEfaRetransPkts.emit(ils.Metrics())
	mb.metricNodeEfaRetransTimeoutEvents.emit(ils.Metrics())
	mb.metricNodeEfaRxBytes.emit(ils.Metrics())
	mb.metricNodeEfaRxDropped.emit(ils.Metrics())
	mb.metricNodeEfaTxBytes.emit(ils.Metrics())
	mb.metricNodeEfaUnresponsiveRemoteEvents.emit(ils.Metrics())

	for _, op := range options {
		op.apply(rm)
	}
	for attr, filter := range mb.resourceAttributeIncludeFilter {
		if val, ok := rm.Resource().Attributes().Get(attr); ok && !filter.Matches(val.AsString()) {
			return
		}
	}
	for attr, filter := range mb.resourceAttributeExcludeFilter {
		if val, ok := rm.Resource().Attributes().Get(attr); ok && filter.Matches(val.AsString()) {
			return
		}
	}

	if ils.Metrics().Len() > 0 {
		mb.updateCapacity(rm)
		rm.MoveTo(mb.metricsBuffer.ResourceMetrics().AppendEmpty())
	}
}

// Emit returns all the metrics accumulated by the metrics builder and updates the internal state to be ready for
// recording another set of metrics. This function will be responsible for applying all the transformations required to
// produce metric representation defined in metadata and user config, e.g. delta or cumulative.
func (mb *MetricsBuilder) Emit(options ...ResourceMetricsOption) pmetric.Metrics {
	mb.EmitForResource(options...)
	metrics := mb.metricsBuffer
	mb.metricsBuffer = pmetric.NewMetrics()
	return metrics
}

// RecordNodeEfaImpairedRemoteConnEventsDataPoint adds a data point to node_efa_impaired_remote_conn_events metric.
func (mb *MetricsBuilder) RecordNodeEfaImpairedRemoteConnEventsDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricNodeEfaImpairedRemoteConnEvents.recordDataPoint(mb.startTime, ts, val)
}

// RecordNodeEfaRdmaReadBytesDataPoint adds a data point to node_efa_rdma_read_bytes metric.
func (mb *MetricsBuilder) RecordNodeEfaRdmaReadBytesDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricNodeEfaRdmaReadBytes.recordDataPoint(mb.startTime, ts, val)
}

// RecordNodeEfaRdmaWriteBytesDataPoint adds a data point to node_efa_rdma_write_bytes metric.
func (mb *MetricsBuilder) RecordNodeEfaRdmaWriteBytesDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricNodeEfaRdmaWriteBytes.recordDataPoint(mb.startTime, ts, val)
}

// RecordNodeEfaRdmaWriteRecvBytesDataPoint adds a data point to node_efa_rdma_write_recv_bytes metric.
func (mb *MetricsBuilder) RecordNodeEfaRdmaWriteRecvBytesDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricNodeEfaRdmaWriteRecvBytes.recordDataPoint(mb.startTime, ts, val)
}

// RecordNodeEfaRetransBytesDataPoint adds a data point to node_efa_retrans_bytes metric.
func (mb *MetricsBuilder) RecordNodeEfaRetransBytesDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricNodeEfaRetransBytes.recordDataPoint(mb.startTime, ts, val)
}

// RecordNodeEfaRetransPktsDataPoint adds a data point to node_efa_retrans_pkts metric.
func (mb *MetricsBuilder) RecordNodeEfaRetransPktsDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricNodeEfaRetransPkts.recordDataPoint(mb.startTime, ts, val)
}

// RecordNodeEfaRetransTimeoutEventsDataPoint adds a data point to node_efa_retrans_timeout_events metric.
func (mb *MetricsBuilder) RecordNodeEfaRetransTimeoutEventsDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricNodeEfaRetransTimeoutEvents.recordDataPoint(mb.startTime, ts, val)
}

// RecordNodeEfaRxBytesDataPoint adds a data point to node_efa_rx_bytes metric.
func (mb *MetricsBuilder) RecordNodeEfaRxBytesDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricNodeEfaRxBytes.recordDataPoint(mb.startTime, ts, val)
}

// RecordNodeEfaRxDroppedDataPoint adds a data point to node_efa_rx_dropped metric.
func (mb *MetricsBuilder) RecordNodeEfaRxDroppedDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricNodeEfaRxDropped.recordDataPoint(mb.startTime, ts, val)
}

// RecordNodeEfaTxBytesDataPoint adds a data point to node_efa_tx_bytes metric.
func (mb *MetricsBuilder) RecordNodeEfaTxBytesDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricNodeEfaTxBytes.recordDataPoint(mb.startTime, ts, val)
}

// RecordNodeEfaUnresponsiveRemoteEventsDataPoint adds a data point to node_efa_unresponsive_remote_events metric.
func (mb *MetricsBuilder) RecordNodeEfaUnresponsiveRemoteEventsDataPoint(ts pcommon.Timestamp, val int64) {
	mb.metricNodeEfaUnresponsiveRemoteEvents.recordDataPoint(mb.startTime, ts, val)
}

// Reset resets metrics builder to its initial state. It should be used when external metrics source is restarted,
// and metrics builder should update its startTime and reset it's internal state accordingly.
func (mb *MetricsBuilder) Reset(options ...MetricBuilderOption) {
	mb.startTime = pcommon.NewTimestampFromTime(time.Now())
	for _, op := range options {
		op.apply(mb)
	}
}
