name: Update changelog

env:
  UPSTREAM: https://github.com/amazon-contributing/opentelemetry-collector-contrib.git
  UPSTREAM_BRANCH: CWQS-761

on:
 push:
    branches:
      - CWQS-*
      - main

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # updated CHANGELOG back to the repository.
      # https://github.blog/changelog/2023-02-02-github-actions-updating-the-default-github_token-permissions-to-read-only/
      contents: write
    steps:
      - name: Get latest commit sha
        id: get-latest-commit
        run: |
            if ["${{ inputs.CommitSha }}" == ""]; then
              echo "sha=$(git ls-remote ${{ env.UPSTREAM }} ${{ env.UPSTREAM_BRANCH }} | awk '{print $1;}')" >> $GITHUB_OUTPUT
            else
              echo "sha=${{ inputs.CommitSha }}" >> $GITHUB_OUTPUT
            fi
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version: ~1.21.1
          cache: false
      - uses: actions/checkout@v1
      - name: run a make update
        run:
          git config --global user.name 'Github Action'
          git config --global user.email 'action@github.com'
          git checkout -b otel-fork-replace-${{ steps.get-latest-commit.outputs.sha }}
          make chlog-update-aws
      - name: switching from HTTPS to SSH
        run: git remote set-url origin https://github.com/amazon-contributing/opentelemetry-collector-contrib.git
      - name: check for changes
        run: |
          git status
      - name: stage changed files
        run: git add .
      - name: commit changed files
        run: |
          git commit -am "Update OTel fork components to https://github.com/amazon-contributing/opentelemetry-collector-contrib/commit/${{ steps.get-latest-commit.outputs.sha }}"
          git push -u origin HEAD
          git config --global --unset user.name
          git config --global --unset user.email

